# For a detailed guide to building and testing on iOS, read the docs:
# https://circleci.com/docs/2.0/testing-ios/

version: 2.1

jobs:
  standard-tests:
    macos:
      xcode: 12.2.0 # Specify the Xcode version to use

    steps:
      - checkout
      - run: "bundle install"
      - run: "bundle exec fastlane standard_tests"

  install-tests:
    macos:
      xcode: 12.2.0 # Specify the Xcode version to use

    steps:
      - checkout
      - run: "bundle install"
      - run: "bundle exec fastlane install_tests"

  integration-tests:
    macos:
      xcode: 12.2.0 # Specify the Xcode version to use

    steps:
      - checkout
      - run: "bundle install"
      - run: "bundle exec fastlane integration_tests"

  ui-and-analyze-tests:
    macos:
      xcode: 12.2.0 # Specify the Xcode version to use

    steps:
      - checkout
      - run: "bundle install"
      - run: "bundle exec fastlane ui_and_analyze_tests"
    
  linting-tests:
    macos:
      xcode: 12.2.0 # Specify the Xcode version to use

    steps:
      - checkout
      - run: "bundle install"
      - run: "bundle add jazzy"
      - run: "bundle exec fastlane linting_tests"

  test-legacy-11:
    macos:
      xcode: 12.2.0 # Specify the Xcode version to use

    steps:
      - checkout
      - run: sudo gem install xcode-install
      - run: sudo xcversion simulators --install="iOS 11.4" --no-progress || true
      - run: "bundle install"
      - run: "bundle exec fastlane legacy_tests_11"

  test-legacy-12:
    macos:
      xcode: 12.2.0 # Specify the Xcode version to use

    steps:
      - checkout
      - run: sudo gem install xcode-install
      - run: sudo xcversion simulators --install="iOS 12.4" --no-progress || true
      - run: "bundle install"
      - run: "bundle exec fastlane legacy_tests_12"      

workflows:
  build-and-test:
    jobs:
      - standard-tests
      - integration-tests
      - install-tests
      - linting-tests
      - ui-and-analyze-tests
      - test-legacy-11
      - test-legacy-12
